t3: 1.0
#####################################
# 対象言語
#####################################
languages:
  - ja_JP
#####################################
# カスタム機能定義
#####################################
info:
  name: aws-s3
  labelName: AWS S3
  customPackage: com.epion_t3.aws.s3
  summary:
    - lang: ja_JP
      contents: "AWSのS3へのアクセスを行う機能を提供します。"
  description:
    - lang: ja_JP
      contents: "AmazonWebService（AWS）のSimpleStorageService（S3）への各種アクセスを行う機能を提供します。事前データの配置、エビデンスの取得などに利用できるPUT、GETを代表とした機能です。"
#####################################
# コマンド定義
#####################################
commands:
  ##########################
  # AwsS3GetObject
  ##########################
  - id: AwsS3GetObject
    evidenceCommand: true
    assertCommand: false
    summary:
      - lang: ja_JP
        contents: "AWS S3からオブジェクトを取得します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: AWS S3から、バケット「${bucket}」、キー「${key}」を取得します。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "AWS S3からオブジェクトを取得します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "AWS S3から同じオブジェクトを取得した場合、別エビデンスとして取得します。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "このコマンドが動作するには、AWSへの接続設定（ [AwsCredentialsProviderConfiguration](https://github.com/epion-tropic-test-tool/epion-t3-aws-core/blob/master/aws-core_spec_ja_JP.md#awscredentialsproviderconfiguration) ）が必要になります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsS3GetObject」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: credentialsConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "資格設定の参照"
      - order: 6
        name: sdkHttpClientConfigRef
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPクライアント設定の参照"
      - order: 7
        name: bucket
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のBucketを指定します。"
      - order: 8
        name: key
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のKeyを指定します。"
  ##########################
  # AwsS3PutObject
  ##########################
  - id: AwsS3PutObject
    evidenceCommand: false
    assertCommand: false
    summary:
      - lang: ja_JP
        contents: "AWS S3にオブジェクトを登録します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "「${target}」を、AWS S3のバケット「${bucket}」、キー「${key}」を取得します。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "AWS S3からオブジェクトを取得します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "AWS S3から同じオブジェクトを取得した場合、別エビデンスとして取得します。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "このコマンドが動作するには、AWSへの接続設定（ [AwsCredentialsProviderConfiguration](https://github.com/epion-tropic-test-tool/epion-t3-aws-core/blob/master/aws-core_spec_ja_JP.md#awscredentialsproviderconfiguration) ）が必要になります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsS3PutObject」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: credentialsConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "資格設定の参照"
      - order: 6
        name: sdkHttpClientConfigRef
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPクライアント設定の参照"
      - order: 7
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "登録対象のファイルの相対パス"
      - order: 8
        name: bucket
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のBucketを指定します。"
      - order: 9
        name: key
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のKeyを指定します。"
  ##########################
  # AwsS3DeleteObject
  ##########################
  - id: AwsS3DeleteObject
    evidenceCommand: false
    assertCommand: false
    summary:
      - lang: ja_JP
        contents: "AWS S3からオブジェクトを取得します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: AWS S3から、バケット「${bucket}」、キー「${key}」を取得します。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "AWS S3からオブジェクトを削除します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "このコマンドが動作するには、AWSへの接続設定（ [AwsCredentialsProviderConfiguration](https://github.com/epion-tropic-test-tool/epion-t3-aws-core/blob/master/aws-core_spec_ja_JP.md#awscredentialsproviderconfiguration) ）が必要になります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsS3DeleteObject」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: credentialsConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "資格設定の参照"
      - order: 6
        name: sdkHttpClientConfigRef
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPクライアント設定の参照"
      - order: 7
        name: bucket
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のBucketを指定します。"
      - order: 8
        name: key
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のKeyを指定します。"
  ##########################
  # AwsS3ListObjects
  ##########################
  - id: AwsS3ListObjects
    evidenceCommand: true
    assertCommand: false
    summary:
      - lang: ja_JP
        contents: "AWS S3からオブジェクトリストを取得します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: AWS S3から、バケット「${bucket}」、「${prefix}」配下のオブジェクトのリストを取得します。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "AWS S3からオブジェクトリストを取得します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "このコマンドが動作するには、AWSへの接続設定（ [AwsCredentialsProviderConfiguration](https://github.com/epion-tropic-test-tool/epion-t3-aws-core/blob/master/aws-core_spec_ja_JP.md#awscredentialsproviderconfiguration) ）が必要になります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsS3ListObjects」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: credentialsConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "資格設定の参照"
      - order: 6
        name: sdkHttpClientConfigRef
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPクライアント設定の参照"
      - order: 7
        name: bucket
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のBucketを指定します。"
      - order: 8
        name: prefix
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のPrefixを指定します。指定しない場合バケット直下となります。"
  ##########################
  # AwsS3DeleteObjects
  ##########################
  - id: AwsS3DeleteObjects
    evidenceCommand: false
    assertCommand: false
    summary:
      - lang: ja_JP
        contents: "AWS S3からオブジェクトリストを削除します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: AWS S3から、バケット「${bucket}」、「${prefix}」配下のオブジェクトを削除します。
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "AWS S3からオブジェクトリストを削除します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "このコマンドが動作するには、AWSへの接続設定（ [AwsCredentialsProviderConfiguration](https://github.com/epion-tropic-test-tool/epion-t3-aws-core/blob/master/aws-core_spec_ja_JP.md#awscredentialsproviderconfiguration) ）が必要になります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsS3DeleteObjects」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: credentialsConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "資格設定の参照"
      - order: 6
        name: sdkHttpClientConfigRef
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPクライアント設定の参照"
      - order: 7
        name: bucket
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のBucketを指定します。"
      - order: 8
        name: prefix
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のPrefixを指定します。指定しない場合バケット直下となります。"
  ##########################
  # AwsS3PutObjects
  ##########################
  - id: AwsS3PutObjects
    evidenceCommand: false
    assertCommand: false
    summary:
      - lang: ja_JP
        contents: "AWS S3に指定されたディレクトリ配下のオブジェクトを登録します。"
    testItem:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "AWS S3のバケット「${bucket}」、Prefix「${prefix}」に対して対象ディレクトリ「$target」配下のファイルをPUTします。"
    function:
      - order: 1
        summary:
          - lang: ja_JP
            contents: "AWS S3へ指定されたディレクトリ配下のオブジェクト（ファイル）を登録します。"
      - order: 2
        summary:
          - lang: ja_JP
            contents: "指定されたディレクトリ直下のファイルのみを対象とします。配下全てのPUTには対応していません。"
      - order: 3
        summary:
          - lang: ja_JP
            contents: "このコマンドが動作するには、AWSへの接続設定（ [AwsCredentialsProviderConfiguration](https://github.com/epion-tropic-test-tool/epion-t3-aws-core/blob/master/aws-core_spec_ja_JP.md#awscredentialsproviderconfiguration) ）が必要になります。"
    structure:
      - order: 1
        name: id
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドのID
      - order: 2
        name: command
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: 「AwsS3PutObjects」固定
      - order: 3
        name: summary
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの概要（任意）
      - order: 4
        name: description
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: コマンドの詳細（任意）
      - order: 5
        name: credentialsConfigRef
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "資格設定の参照"
      - order: 6
        name: sdkHttpClientConfigRef
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "HTTPクライアント設定の参照"
      - order: 7
        name: target
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "登録対象のファイルの相対パス"
      - order: 8
        name: bucket
        required: true
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のBucketを指定します。"
      - order: 9
        name: prefix
        required: false
        type: string
        summary:
          - lang: ja_JP
            contents: "s3のPrefixを指定します。指定しない場合バケット直下となります。"
#####################################
# メッセージ定義
#####################################
messages:
  - id: com.epion_t3.aws.s3.err.9001
    message:
      - lang: ja_JP
        contents: "対象（target）のバケット及びキーへアクセスできません.Bucket:{0}, Path:{1}"
  - id: com.epion_t3.aws.s3.err.9002
    message:
      - lang: ja_JP
        contents: "対象（target）のバケット及びキーは存在しません.Bucket:{0}, Path:{1}"
  - id: com.epion_t3.aws.s3.err.9003
    message:
      - lang: ja_JP
        contents: "対象（target）のバケット及びプレフィックスは存在しません.Bucket:{0}, Prefix:{1}"
  - id: com.epion_t3.aws.s3.err.9004
    message:
      - lang: ja_JP
        contents: "対象（target）はディレクトリを指定する必要があります. Target:{0}"
  - id: com.epion_t3.aws.s3.inf.0001
    message:
      - lang: ja_JP
        contents: "削除対象のオブジェクトが存在しませんでした. Target:{0}"